### ISSUE TITLE
Webpack build failure when using carbon-components-react

### ISSUE THREAD

**Issue by ajborley** [carbon-design-system/carbon-components-react#525]
## Detailed description

We have added  carbon-components-react to our package.json, but we are seeing babel failures when running our webpack build:

```
ERROR in ./node_modules/carbon-components-react/es/index.js
Module build failed: Error: Couldn't find preset "./scripts/env" relative to directory "/Users/ajborley/qp/qp-ui/node_modules/carbon-components-react"
    at /Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:422:13)
```

We have tried the `env`, `react` and `react-app` babel presets in our .babelrc and/or webpack config but none of them appear to affect this error. Has anyone seen anything like this before?

Additionally we previously got a babel plugin error in the carbon-components-react code and had to install the `babel-plugin-transform-object-assign` dependency to get around that (which was when we hit this latest babel issue).

We think we've done everything required to use carbon-components-react, but it feels like we are pointing at the wrong location or something..

**Comment by ajborley** [comment]
The previous plugin error is:
```
ERROR in ./node_modules/carbon-components-react/es/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/Users/ajborley/qp/qp-ui/node_modules/carbon-components-react/package.json" at 0, attempted to resolve relative to "/Users/ajborley/qp/qp-ui/node_modules/carbon-components-react"
    at /Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/ajborley/qp/qp-ui/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/ajborley/qp/qp-ui/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:422:13)
```

This was worked around by install the `babel-plugin-transform-object-assign` as a dependency.

**Comment by ajborley** [comment]
This was due to a webpack configuration error - I needed to ensure the babel-loader config excluded the `node_modules` dir, like this:
```
  module: {
    rules: [{
      test: /\.(jsx|js)?$/,
      exclude: /(node_modules)/,  <--- the missing line
      use: [{
        loader: "babel-loader",
        options: {
          cacheDirectory: true,
          presets: ['react', 'env'] // Transpiles JSX and ES6
        }
      }]
    }]
  }
```
